server:
  port: 1998  # Spring boot Server port

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test
    username: Cature

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  jwt:
    secret: anwjrdmldhdlsqkddlskxkskTekejaqufkdkrekdemfdk
    subject: catureJwt
    claims:
      user-id: uid
      authority: ath
      email: eml
      platform-id: pid

loggin.level:
  org.hibernate.type: trace

